//
//  LoginRouter.swift
//  BankApp
//
//  Created by Gabriel Henrique Santos Pereira on 12/04/19.
//  Copyright (c) 2019 Gabriel Henrique Santos Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeTosegueExtractViewControllerWithSegue(_ segue: UIStoryboardSegue?)
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    func routeTosegueExtractViewControllerWithSegue(_ segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationViewController = segue.destination as! ExtractViewController
            var destinationDataStore = destinationViewController.router!.dataStore!
            
            sendAccountInformation(source: dataStore!, destination: &destinationDataStore)
        }
    }
    
    func navigateToExtractView(source: LoginViewController, destination: ExtractViewController) {
        source.show(destination, sender: nil)
    }
    
    func sendAccountInformation(source: LoginDataStore, destination: inout ExtractDataStore) {
        destination.userAccount = source.userAccount
    }
}
