//
//  LoginRouter.swift
//  BankApp
//
//  Created by Gabriel Henrique Santos Pereira on 12/04/19.
//  Copyright (c) 2019 Gabriel Henrique Santos Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
//    func routToExtract(segue: UIStoryboardSegue?)
    func segueToViewController(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing {
    // var dataStore: LocationDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    
    func segueToViewController(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationViewController = segue.destination as! ExtractViewController
            let destinationDataStore = destinationViewController.router!.dataStore!
        }
    }
    
//    var dataStore: LocationDataStore?
//
//    func routeToCurrency(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! ExtractViewController
//            let destinationDS = destinationVC.router!.dataStore!
//
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        }
//    }
//
//    func passDataToSomewhere(source: LocationDataStore, destination: input CurrencyDataStore) {
//        destination.userAccount = source.userAccount
//    }
}
