//
//  ExtractInteractor.swift
//  BankApp
//
//  Created by Gabriel Henrique Santos Pereira on 12/04/19.
//  Copyright (c) 2019 Gabriel Henrique Santos Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExtractBusinessLogic {
    func getUserAccountData() -> Void
}

protocol ExtractDataStore {
    var userAccount: LoginResponse.UserAccount? { get set }
}

class ExtractInteractor: ExtractBusinessLogic, ExtractDataStore {
    var loginResponse: LoginResponse?
    var userAccount: LoginResponse.UserAccount?
    var presenter: ExtractPresentationLogic?
    var worker: ExtractWorker?
    
    // MARK: Do something
    func getUserAccountData() {
        if let userAccount = self.userAccount {
            print("ExtractInteractor", userAccount)
            self.presenter?.presentUserAccountData(userAccountData: userAccount)
        }
    }
}
