//
//  ExtractInteractor.swift
//  BankApp
//
//  Created by Gabriel Henrique Santos Pereira on 12/04/19.
//  Copyright (c) 2019 Gabriel Henrique Santos Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExtractBusinessLogic {
    func getExtractListByUser(userId: String) -> Void
    func getUserAccountData() -> Void
}

protocol ExtractDataStore {
    var userAccount: LoginResponse.UserAccount? { get set }
}

class ExtractInteractor: ExtractBusinessLogic, ExtractDataStore {
    var loginResponse: LoginResponse?
    var userAccount: LoginResponse.UserAccount?
    var presenter: ExtractPresentationLogic?
    var worker: ExtractWorker?
    
    // MARK: Get the extract list by user
    func getExtractListByUser(userId: String) {
        worker = ExtractWorker()
        
        worker?.getExtractList(extractId: userId, responseRequest: { response in
            self.presenter?.presentExtractList(extract: response.extractData)
        })
    }
    
    // MARK: Present user account information
    func getUserAccountData() {
        if let userAccount = self.userAccount {
            self.presenter?.presentUserAccountData(userAccountData: userAccount)
        }
    }
}
