//
//  ExtractPresenter.swift
//  BankApp
//
//  Created by Gabriel Henrique Santos Pereira on 12/04/19.
//  Copyright (c) 2019 Gabriel Henrique Santos Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExtractPresentationLogic {
    func presentUserAccountData(userAccountData: LoginResponse.UserAccount) -> Void
    func presentExtractList(extract: [ExtractResponse.ExtractData]?) -> Void
}

class ExtractPresenter: ExtractPresentationLogic {
    weak var viewController: ExtractDisplayLogic?
    
    func presentExtractList(extract: [ExtractResponse.ExtractData]?) {
        if let extract = extract {
            self.viewController?.success(extract: extract)
        }
    }
    
    // MARK: Present user account data inside viewController
    func presentUserAccountData(userAccountData: LoginResponse.UserAccount) {
        self.viewController?.renderUserAccountData(userData: userAccountData)
    }
}
